language: php

php:
  - 7.4

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - php artisan key:generate
  - sleep 10

script:
  - ./vendor/bin/phpcs
  - vendor/bin/phpunit

services:
  - redis-server
  - elasticsearch