<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Traits\AdminUser;
use App\User;
use App\Role;
use App\Permission;
use Tests\TestCase;

class RoleTest extends TestCase
{
    use RefreshDatabase, AdminUser;
    
    public function setUp(): void
    {
        parent::setUp();        
        $this->actingAs($this->createAdminUser());
    }
    
    /** @test */
    public function generating_admin_user_via_seeds_works_correctly()
    {       
        $this->assertCount(1, Role::all());
        $this->assertCount(1, User::all());
        $this->assertCount(32, Permission::all());        
    }

    /** @test */
    public function a_role_can_be_added_to_the_table_through_the_form()
    {
        $this->post('/dashboard/roles', ['title' => 'Moderator',])
                ->assertSessionHas('success_message')
                ->assertStatus(302)
                ->assertRedirect('/dashboard/roles');
        //because Admin role generated by default via seed
        $this->assertCount(2, Role::all());
    }
    
    /** @test */
    public function validation_title_is_at_least_two_characters() 
    {
        $this->post('/dashboard/roles', ['title' => 'A',])
                ->assertSessionHasErrors('title');
        $messages = session('errors')->getMessages();
        $this->assertEquals($messages['title'][0], 'Поле должно быть мин 2 символа(ов).');
        $this->assertCount(1, Role::all());
    }
    
    /** @test */
    public function validation_a_title_is_required() 
    {
        $this->post('/dashboard/roles', ['title' => '',])
                ->assertSessionHasErrors('title');
        $this->assertCount(1, Role::all());
    }
    
    /** @test */
    public function validation_a_title_should_be_max_30_characters() 
    {
        $this->post('/dashboard/roles', [
            'title' => 'Quaerat qui fuga minima sunt voluptatem id',
            ])
                ->assertSessionHasErrors('title');
        $messages = session('errors')->getMessages();
        $this->assertEquals($messages['title'][0], 'Поле не должно быть больше 30 символа(ов).');
        $this->assertCount(1, Role::all());
    }
    
    /** @test */
    public function a_role_can_be_updated() 
    {
        $role = factory(Role::class)->create();
        $this->patch('/dashboard/roles/' . $role->id, ['title' => 'Guest',])
                ->assertSessionHas('success_message')
                ->assertRedirect('/dashboard/roles/');    
        $this->assertEquals(session('success_message'), 'Role Updated Successfully!');
        $this->assertDatabaseMissing('roles', $role->toArray());
        $this->assertDatabaseHas('roles', ['title' => 'Guest']);
    }
    
    /** @test */
    public function a_role_can_be_deleted()
    {
        $role = factory(Role::class)->create();
        $this->assertCount(2, Role::all());       
        $this->delete('/dashboard/roles/' . $role->id);
        $this->assertCount(1, Role::all());
        $this->assertDeleted($role);
    }
}
