<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Traits\AdminUser;
use Tests\Traits\GuestUser;
use App\User;
use App\Role;
use App\Permission;
use Tests\TestCase;

class RoleTest extends TestCase
{
    use RefreshDatabase, AdminUser, GuestUser;
    
    /** @test */
    public function generating_admin_user_via_seeds_works_correctly()
    {
        $this->actingAs($this->createAdminUser());
        $this->assertCount(1, Role::all());
        $this->assertCount(1, User::all());
        $this->assertCount(32, Permission::all());        
    }

    /** @test */
    public function generating_guest_user_via_factory_works_correctly()
    {
        $this->actingAs($this->createGuestUser());
        $this->assertCount(1, Role::all());
        $this->assertCount(1, User::all());
        $this->assertCount(1, Permission::all());        
    }    
    
    /** @test */
    public function a_role_can_be_added_to_the_table_through_the_form()
    {
        $this->actingAs($this->createAdminUser());
        $response = $this->post('/dashboard/roles', [
            'title' => 'Moderator',
        ])->assertSessionHas('success_message')->assertStatus(302);
        $response->assertRedirect('/dashboard/roles');
        //because Admin role generated by default via seed
        $this->assertCount(2, Role::all());
    }
    
    /** @test */
    public function validation_title_is_at_least_two_characters() 
    {
        $this->actingAs($this->createAdminUser());
        $response = $this->post('/dashboard/roles', [
            'title' => 'A',
        ]);
        $response->assertSessionHasErrors('title');
        $messages = session('errors')->getMessages();
        $this->assertEquals($messages['title'][0], 'Поле должно быть мин 2 символа(ов).');
        //because Admin role generated by default via seed
        $this->assertCount(1, Role::all());
    }
    
    /** @test */
    public function validation_a_title_is_required() 
    {
        $this->actingAs($this->createAdminUser());
        $response = $this->post('/dashboard/roles', [
            'title' => '',
        ]);
        $response->assertSessionHasErrors('title');
        //because Admin role generated by default via seed
        $this->assertCount(1, Role::all());
    }
    
    /** @test */
    public function validation_a_title_should_be_max_30_characters() 
    {
        $this->actingAs($this->createAdminUser());
        $response = $this->post('/dashboard/roles', [
            'title' => 'Quaerat qui fuga minima sunt voluptatem id',
        ]);
        $response->assertSessionHasErrors('title');
        $messages = session('errors')->getMessages();
        $this->assertEquals($messages['title'][0], 'Поле не должно быть больше 30 символа(ов).');
        //because Admin role generated by default via seed
        $this->assertCount(1, Role::all());
    }
    
    /** @test */
    public function a_role_can_be_updated() 
    {
        $this->actingAs($this->createAdminUser());
        factory(Role::class)->create();
        $role = Role::first();
        $response = $this->patch('/dashboard/roles/' . $role->id, [
            'title' => 'Guest',
        ])->assertSessionHas('success_message');
        $this->assertEquals('Guest', Role::first()->title);
        $this->assertEquals(session('success_message'), 'Role Updated Successfully!');
        $this->assertDatabaseMissing('roles', $role->toArray());
        $this->assertDatabaseHas('roles', ['title' => 'Guest']);
        $response->assertRedirect('/dashboard/roles/');
    }
    
    /** @test */
    public function a_role_can_be_deleted()
    {
        $this->actingAs($this->createAdminUser());
        factory(Role::class)->create();
        $this->assertCount(2, Role::all());
        $role = Role::first();        
        $this->delete('/dashboard/roles/' . $role->id);
        $this->assertCount(1, Role::all());
        $this->assertDeleted($role);
    }
}
